export interface ConceptCard {
  title: string
  emoji: string
  steps: string[]
  example: string
  tip: string
}

export const CONCEPT_CARDS: Record<string, ConceptCard> = {
  rational_numbers: {
    title: 'Operations with Rational Numbers',
    emoji: '➕➖',
    steps: [
      'To ADD/SUBTRACT negatives: same sign → add and keep sign. Different signs → subtract smaller from larger, keep sign of larger.',
      'To MULTIPLY/DIVIDE: same signs → positive result. Different signs → negative result.',
      'For FRACTIONS: find common denominator first, then add/subtract numerators.',
      'ABSOLUTE VALUE: always positive — it\'s the distance from zero.',
    ],
    example: '-3 + (-5) = -8 (same sign, add) | -3 + 7 = 4 (different signs, 7-3=4, keep positive)',
    tip: '💡 Think of a number line — going left is negative, right is positive!',
  },
  proportional: {
    title: 'Proportional Relationships & Percent Change',
    emoji: '📐',
    steps: [
      'CONSTANT OF PROPORTIONALITY (k): k = y ÷ x. If k is the same for all pairs, it\'s proportional.',
      'PERCENT CHANGE: ((New - Original) ÷ Original) × 100',
      'PERCENT INCREASE: result is positive. PERCENT DECREASE: result is negative.',
      'SIMPLE INTEREST: I = P × r × t (Principal × rate × time)',
    ],
    example: 'Original: $50, New: $65. Change = (65-50)/50 × 100 = 30% increase',
    tip: '💡 For percent change, always divide by the ORIGINAL (starting) value!',
  },
  expressions_equations: {
    title: 'Two-Step Equations & Inequalities',
    emoji: '🔢',
    steps: [
      'SOLVING EQUATIONS: undo operations in reverse order (PEMDAS backwards).',
      'Step 1: Add or subtract to isolate the variable term.',
      'Step 2: Multiply or divide to solve for the variable.',
      'INEQUALITIES: same steps, but flip the sign when multiplying/dividing by a NEGATIVE.',
      'CHECK: substitute your answer back into the original equation.',
    ],
    example: '2x + 3 = 11 → subtract 3: 2x = 8 → divide by 2: x = 4 ✓',
    tip: '💡 Whatever you do to one side, do to the other side!',
  },
  geometry: {
    title: 'Circles, Angles & Area/Volume',
    emoji: '📏',
    steps: [
      'CIRCLE: Area = π × r² | Circumference = 2 × π × r (use π ≈ 3.14)',
      'COMPLEMENTARY angles: add to 90°. SUPPLEMENTARY: add to 180°.',
      'VERTICAL angles: always equal. TRIANGLE angles: always add to 180°.',
      'SURFACE AREA: sum of ALL face areas.',
      'VOLUME of prism: Base Area × height.',
    ],
    example: 'Circle radius = 5: Area = 3.14 × 5² = 3.14 × 25 = 78.5 sq units',
    tip: '💡 r is radius (center to edge), d is diameter (edge to edge). d = 2r!',
  },
  statistics_probability: {
    title: 'Probability & Statistics',
    emoji: '🎲',
    steps: [
      'PROBABILITY = favorable outcomes ÷ total outcomes (always between 0 and 1)',
      'THEORETICAL: what should happen. EXPERIMENTAL: what actually happened.',
      'INDEPENDENT events: P(A and B) = P(A) × P(B)',
      'DEPENDENT events: P(A then B) = P(A) × P(B after A happened)',
      'MEDIAN: arrange in order first, then find middle value.',
    ],
    example: 'P(rolling 3 on a die) = 1/6 ≈ 0.167 or 16.7%',
    tip: '💡 Always SORT the data before finding median or range!',
  },
  number_operations: {
    title: 'Number Operations & Exponents',
    emoji: '🧮',
    steps: [
      'EXPONENTS: base^power means multiply base by itself "power" times. 2³ = 2×2×2 = 8',
      'SCIENTIFIC NOTATION: a × 10^n where 1 ≤ a < 10',
      'SQUARE ROOTS: √25 = 5 because 5² = 25. Perfect squares: 1,4,9,16,25,36,49,64,81,100',
      'ORDER OF OPERATIONS (PEMDAS): Parentheses → Exponents → Multiply/Divide → Add/Subtract',
    ],
    example: '3² × (4 + 1) - 6 = 9 × 5 - 6 = 45 - 6 = 39',
    tip: '💡 PEMDAS: Please Excuse My Dear Aunt Sally!',
  },
  ratio_proportion: {
    title: 'Ratios, Rates & Proportional Reasoning',
    emoji: '📐',
    steps: [
      'UNIT RATE: divide to find "per 1". 150 miles in 3 hours = 50 mph.',
      'SLOPE = rise ÷ run = change in y ÷ change in x',
      'PERCENT CHANGE: ((New - Original) ÷ Original) × 100',
      'TAX/TIP: multiply total by decimal. 20% tip on $45 = 0.20 × 45 = $9',
      'DISCOUNT: multiply by (1 - discount%). 30% off $80 = 0.70 × 80 = $56',
    ],
    example: 'Slope from (0,0) to (3,6): rise = 6, run = 3, slope = 6/3 = 2',
    tip: '💡 Slope is the constant of proportionality k in y = kx!',
  },
  algebra: {
    title: 'Algebra & Linear Functions',
    emoji: '🔢',
    steps: [
      'SLOPE-INTERCEPT: y = mx + b (m = slope, b = y-intercept)',
      'SLOPE: m = (y₂ - y₁) ÷ (x₂ - x₁)',
      'To GRAPH: plot b on y-axis, then use slope (rise/run) to find next points.',
      'FUNCTION: each input has exactly ONE output. Check with vertical line test.',
      'COMBINING LIKE TERMS: only combine terms with same variable and exponent.',
    ],
    example: 'y = 2x + 3: slope=2 (up 2, right 1), y-intercept=3 (starts at (0,3))',
    tip: '💡 "b" in y=mx+b is where the line crosses the y-axis (x=0)!',
  },
  geometry_adv: {
    title: 'Advanced Geometry & Transformations',
    emoji: '📏',
    steps: [
      'PYTHAGOREAN THEOREM: a² + b² = c² (c is always the longest side, hypotenuse)',
      'TRANSFORMATIONS: Translation (slide), Reflection (flip), Rotation (turn), Dilation (resize)',
      'DILATION: multiply all coordinates by scale factor k.',
      'REFLECTION over x-axis: (x, y) → (x, -y). Over y-axis: (x, y) → (-x, y)',
      'ROTATION 90° clockwise: (x, y) → (y, -x)',
    ],
    example: 'Right triangle: legs 3 and 4. Hypotenuse: √(3²+4²) = √(9+16) = √25 = 5',
    tip: '💡 3-4-5 is the most common Pythagorean triple — memorize it!',
  },
  data_probability: {
    title: 'Data Analysis & Probability',
    emoji: '🎲',
    steps: [
      'SCATTER PLOT: positive correlation (both go up), negative (one up, one down), no correlation.',
      'TREND LINE (line of best fit): draw through middle of data, roughly equal points above and below.',
      'COMPOUND PROBABILITY — Independent: P(A and B) = P(A) × P(B)',
      'COMPOUND PROBABILITY — Dependent: P(A then B) = P(A) × P(B|A)',
      'STATISTICAL INFERENCE: a random sample should represent the whole population.',
    ],
    example: 'Bag: 3 red, 2 blue. P(red then blue, no replace) = 3/5 × 2/4 = 6/20 = 3/10',
    tip: '💡 "Without replacement" means dependent events — the second probability changes!',
  },
  ratios_basic: {
    title: 'Ratios, Equivalent Ratios & Unit Rates',
    emoji: '⚖️',
    steps: [
      'A RATIO compares two amounts: 3 red to 5 blue is written 3:5 or 3/5.',
      'PART-TO-PART: red : blue = 3 : 5. PART-TO-WHOLE: red : total = 3 : 8. Read the question carefully — they are NOT the same!',
      'EQUIVALENT RATIOS: multiply or divide BOTH numbers by the same value. 3:5 = 6:10 = 9:15.',
      'To SOLVE a proportion: cross multiply. 3/5 = x/20 → 5x = 60 → x = 12.',
      'UNIT RATE: divide to get "per 1". $6 for 4 bagels → 6 ÷ 4 = $1.50 per bagel.',
      'BEST BUY: find the unit rate for each option, then compare — lowest price per unit wins.',
    ],
    example: 'Recipe uses 2 cups flour to 3 cups milk. For 9 cups milk: 3 × 3 = 9, so flour = 2 × 3 = 6 cups.',
    tip: '💡 Label your numbers! Writing "flour/milk" on both sides of the proportion stops you from flipping it.',
  },
  mean_average: {
    title: 'Mean, Median, Mode & Range',
    emoji: '📊',
    steps: [
      'MEAN (average) = add all the values ÷ how many values there are.',
      'MEDIAN = middle value AFTER sorting least to greatest. Even count? Average the two middle numbers.',
      'MODE = value that appears most often. RANGE = biggest − smallest.',
      'MISSING VALUE problems: total needed = mean × number of values. Then subtract the scores you already have.',
      'A new value ABOVE the mean pulls the mean up; BELOW the mean pulls it down. Outliers move the mean a lot, the median barely.',
    ],
    example: 'Tests: 88, 92, 79, 85. Mean = (88+92+79+85) ÷ 4 = 344 ÷ 4 = 86. Need a 90 average over 5 tests? 90 × 5 = 450; 450 − 344 = 106 — not possible!',
    tip: '💡 For "what score do I need" problems, always start with mean × number of values = total.',
  },
  time_elapsed: {
    title: 'Time & Elapsed Time',
    emoji: '⏰',
    steps: [
      'ELAPSED TIME = end time − start time. Count up in chunks: to the next hour, then whole hours, then the extra minutes.',
      'Remember 60 minutes = 1 hour — when you borrow, you borrow 60, not 100.',
      'CONVERT before you calculate: 2 h 15 min = 135 min. 1.5 h = 90 min (0.5 × 60), NOT 1 h 50 min.',
      'CROSSING NOON/MIDNIGHT: 11:40 a.m. to 1:20 p.m. → 20 min to noon + 1 h 20 min = 1 h 40 min.',
      'WORKING BACKWARD: if something takes 45 min and must END at 3:10, subtract → start at 2:25.',
    ],
    example: '9:45 a.m. to 1:20 p.m.: 15 min → 10:00, then 3 h → 1:00, then 20 min = 3 h 35 min total.',
    tip: '💡 Decimal hours are the #1 trap: 3.25 hours = 3 h 15 min, not 3 h 25 min!',
  },
  speed_distance: {
    title: 'Speed, Distance & Time',
    emoji: '🚗',
    steps: [
      'The formula triangle: DISTANCE = speed × time | SPEED = distance ÷ time | TIME = distance ÷ speed.',
      'UNITS MUST MATCH: if speed is in miles per HOUR, time must be in HOURS. 30 min = 0.5 h.',
      'AVERAGE SPEED = TOTAL distance ÷ TOTAL time — never average the two speeds!',
      'To compare speeds, convert both to the same unit rate (e.g. miles per hour) first.',
      'CHECK: a bigger speed with the same time must give a bigger distance. If it does not, you divided when you should have multiplied.',
    ],
    example: '150 miles in 2.5 hours → 150 ÷ 2.5 = 60 mph. At 60 mph for 45 min: 60 × 0.75 = 45 miles.',
    tip: '💡 Write the units next to every number. If they cancel to "miles," your setup is right.',
  },
  area_figures: {
    title: 'Area, Parallelograms & Surface Area',
    emoji: '🟦',
    steps: [
      'PARALLELOGRAM: Area = base × HEIGHT. The height is the straight-up (perpendicular) dashed line — NOT the slanted side.',
      'WHY it works: cut the triangle off one end and slide it to the other — the parallelogram REARRANGES into a rectangle with the same base and height.',
      'Any side can be the base, but the height must be perpendicular to THAT base. Each base has its own matching height.',
      'TRIANGLE: A = ½ × base × height (half of a parallelogram). TRAPEZOID: A = ½ × (base₁ + base₂) × height.',
      'COMPOSITE figures: DECOMPOSE into rectangles/triangles and add, or ENCLOSE in a big rectangle and subtract the corners.',
      'SURFACE AREA = total area of every face. Unfold the shape into a NET, find each face, add them all up.',
      'Rectangular prism: SA = 2lw + 2lh + 2wh (three pairs of matching faces). Area/SA use SQUARE units (cm²).',
    ],
    example: 'Parallelogram b = 12 cm, h = 8 cm, slanted side 10 cm → A = 12 × 8 = 96 cm² (12 × 10 = 120 is the trap!). Box 5 × 3 × 2: SA = 2(15) + 2(10) + 2(6) = 62 cm².',
    tip: '💡 Three numbers on a parallelogram? One is the slanted side and it is bait. Use the dashed height.',
  },
  rates_percentages: {
    title: 'Rates & Percentages',
    emoji: '💯',
    steps: [
      'UNIT RATE = how much for ONE. $12 for 4 lb → 12 ÷ 4 = $3 per lb. Every pair of equivalent ratios has the same unit rate.',
      'Each ratio has TWO unit rates: 12 ÷ 4 = $3 per lb, or 4 ÷ 12 = ⅓ lb per dollar. Pick the one the question asks for.',
      'PERCENT means "per 100": 35% = 35/100 = 0.35.',
      'Find the PART: part = percent × whole. 30% of 80 = 0.30 × 80 = 24.',
      'Find the WHOLE: whole = part ÷ percent. 24 is 30% of what? 24 ÷ 0.30 = 80.',
      'Find the PERCENT: percent = part ÷ whole × 100. 24 out of 80 → 24 ÷ 80 = 0.3 = 30%.',
      'DOUBLE NUMBER LINE: put 0% and 100% (the whole) on it, then mark 10%, 25%, 50% as landmarks.',
    ],
    example: '15 is 25% of what? 25% is ¼, so the whole is 15 × 4 = 60. Check: ¼ of 60 = 15 ✓',
    tip: '💡 Name the three pieces — part, whole, percent — and circle which one is missing before you calculate.',
  },
  dividing_fractions: {
    title: 'Dividing Fractions',
    emoji: '➗',
    steps: [
      'Ask the question: "HOW MANY GROUPS of ⅓ fit in 2?" → 2 ÷ ⅓ = 6.',
      'Or: "HOW MUCH IN 1 GROUP?" — if ¾ of a bag is 6 cups, a whole bag is 6 ÷ ¾ = 8 cups.',
      'RECIPROCAL: flip the divisor. a/b ÷ c/d = a/b × d/c. ("Keep, change, flip")',
      'COMMON DENOMINATORS works too: 3/4 ÷ 1/8 = 6/8 ÷ 1/8 = 6 ÷ 1 = 6.',
      'MIXED NUMBERS: turn them into improper fractions FIRST. 2½ = 5/2.',
      'Dividing by a fraction less than 1 makes the answer BIGGER — that is a good way to check.',
    ],
    example: '2½ ÷ ¾ = 5/2 ÷ 3/4 = 5/2 × 4/3 = 20/6 = 3⅓. "3⅓ groups of ¾ fit in 2½."',
    tip: '💡 Only flip the SECOND fraction (the divisor) — never the first one!',
  },
  decimal_arithmetic: {
    title: 'Decimal Arithmetic',
    emoji: '🔟',
    steps: [
      'ADD/SUBTRACT: line up the decimal points. Fill empty spots with zeros: 7 − 2.35 → 7.00 − 2.35 = 4.65.',
      'MULTIPLY: ignore the decimals, multiply, then count the total decimal places in both factors. 0.4 × 0.3 → 12 → 0.12.',
      'DIVIDE by a decimal: move the decimal in the divisor to make it a whole number, and move the dividend the SAME number of places. 4.5 ÷ 0.15 → 450 ÷ 15 = 30.',
      'ESTIMATE first: 3.9 × 5.1 ≈ 4 × 5 = 20. If your answer is 1.989 or 198.9, a decimal point slipped.',
      'Money problems are decimal problems — round to the nearest cent (hundredths) at the end.',
    ],
    example: '2.6 × 1.25: 26 × 125 = 3250; 1 + 2 = 3 decimal places → 3.250 = 3.25',
    tip: '💡 Multiplying by a decimal less than 1 makes the number SMALLER. Dividing by one makes it BIGGER.',
  },
  expressions_6: {
    title: 'Expressions & Equations (Grade 6)',
    emoji: '🟰',
    steps: [
      'The EQUAL SIGN is a balance: both sides have the same value. Whatever you do to one side, do to the other.',
      'Solve x + 7 = 19 by subtracting 7 from both sides: x = 12. Solve 4x = 28 by dividing both sides by 4: x = 7.',
      'EQUIVALENT EXPRESSIONS are equal for EVERY value of the variable: 3(x + 2) = 3x + 6 (distributive property).',
      'COMBINE LIKE TERMS: 2x + 5y + 3x = 5x + 5y. x and y are different — they cannot combine.',
      'EXPONENTS: 3⁴ = 3 × 3 × 3 × 3 = 81, not 3 × 4. Order of operations: exponents come before multiplying.',
      'WRITING equations from words: "5 more than a number is 12" → n + 5 = 12.',
    ],
    example: 'Evaluate 2x² + 3 when x = 4: 4² = 16 → 2 × 16 = 32 → 32 + 3 = 35',
    tip: '💡 Test equivalent expressions by plugging in a number like 2 — if both sides match, you are probably right.',
  },
}
